name: build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Reuse ccache directory
        uses: actions/cache@v3
        with:
          path: ~/.ccache
          key: '${{matrix.os}} ${{matrix.info}} ccache-dir ${{github.ref}} run-${{github.run_number}}'
          restore-keys: |
            ${{matrix.os}} ${{matrix.info}} ccache-dir ${{github.ref}} run-'
            ${{matrix.os}} ${{matrix.info}} ccache-


      - name: Setup ccache
        run : |
          sudo apt install -y ccache
          ccache -M 2.0GB
          ccache -s

      - name: Run conan
        run : |
          mkdir -p ${{github.workspace}}/build
          cd ${{github.workspace}}/build
          conan install ..

      - name: Run cmake
        run : |
          cmake -S ${{github.workspace}} -B ${{github.workspace}}/build

      - name: Build
        run: cmake --build ${{github.workspace}}/build

